[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "template"
path = "src/template/main.rs"

[[bin]]
name = "day1_2021"
path = "src/2021/day1/main.rs"

[[bin]]
name = "day2_2021"
path = "src/2021/day2/main.rs"

[[bin]]
name = "day4_2021"
path = "src/2021/day4/main.rs"

[[bin]]
name = "day5_2021"
path = "src/2021/day5/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
